### ISSUE TITLE
box-decoration-break on spans

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/music-map-story#22]
I learned this from the love and ai piece: there's a relatively new css property that you can set to `box-decoration-break: clone` that will add the correct padding to all your spans regardless of where the line break occurs. [Works](https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break) on everything except IE, because of course.

**Comment by matthewfdaniels** [comment]
wasn't working for me in chrome. does it work for you? maybe i need one more property to get to owrk?

**Comment by jadiehm** [comment]
It's weird if you're just using it in the developer console it doesn't work unless you check and uncheck another element, then it shows up. But I can get it to work if it's originally there.
